### ISSUE TITLE
Set up lambda for emails

### ISSUE THREAD

**Issue by RudraPatel2003** [utk-cs340-fall24/SolSync#42]
This lambda takes in an email address and an html string and sends it to sendgrid.

**Comment by baekay000** [comment]
Sengrid refused our account, so we will be using mailgun

<img width="1010" alt="image" src="https://github.com/user-attachments/assets/c009a314-a7da-4fac-86ed-b4caaf70a2d2">

<img width="693" alt="image" src="https://github.com/user-attachments/assets/05ba18e7-1f9b-4e38-bfa1-6493b0e05d5b">

**Comment by baekay000** [comment]
<img width="1319" alt="image" src="https://github.com/user-attachments/assets/3130c24e-d07d-4c30-a8a1-f99227157d7e">
